export enum LocalStorageKeys {

  TEST_ATTEMPT_QUESTION_URM = 'TEST_ATTEMPT_QUESTION_URM',
  CHECK_FOR_EXISTING_ATTEMPT = 'CHECK_FOR_EXISTING_ATTEMPT',
  TEST_ATTEMPT_DATA = 'TEST_ATTEMPT_DATA',
  RESUME_TEST_ID = 'RESUME_TEST_ID',
}
